# Dependencies
markdown: kramdown
highlighter: rouge

# Gems
gems:
  - jekyll-feed
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-seo-tag

# Settings
exclude:
  [
    CNAME,
    README.md,
    LICENSE.md,
    .gitignore,
    package.json,
    yarn.lock,
    _js,
    _scss,
    _images,
    gulpfile.js,
    gulpconfig.js,
    node_modules,
    gemfile,
    Gemfile.lock,
    lint-staged.config.js,
    prettier.config.js,
  ]
permalink: /:title/
compress_html:
  clippings: all
  comments: all

# Site meta
title: 'Autumn'
tagline: 'Embrace change.'
description: 'Autumn is a minimalist Jekyll theme made by <a href="https://connorbaer.co/" target="_blank" rel="noopener noreferrer">Connor</a>.'
keywords: 'connor, baer, bear, designer, developer, traveller, design, code, jekyll, autumn, theme, for hire'
url: https://connor-baer.github.io
baseurl: /autumn
assets: /assets
images: /images
image: index-large.jpg
logo: /assets/icons/apple-icon-144x144.png
dark_theme: false

author:
  name: Connor Bär
  bio: Hi, I'm Connor, the author of this blog. Nice to meet you!
  image: author
  url: https://connorbaer.co
  email: hello@connorbaer.co
  twitter: connor_baer

social:
  twitter: https://twitter.com/connor_baer
  instagram: https://instagram.com/connor_baer
  github: https://github.com/connor-baer/autumn
  medium: https://medium.com/@connor_baer

version: 4.0.0

github:
  repo: https://github.com/connor-baer/autumn

# Integrations
# typekit:              fcv7rfe

google_fonts:
  Overpass: 400, 600, 800

google_analytics_key: UA-94021817-2
# google_site_verification: Z-pc_HPc4XNBz8xg1fgtxO2MSIYLirZc2jWTNq0bJyM

# Content
excerpt_separator: <!-- Read more -->

navigation:
  GitHub: https://github.com/connor-baer/autumn
